# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    windows-build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "18.x"

            - name: Install Node.js dependencies
              run: npm ci

            - name: Build win-x64
              run: npm run-script dist:64

            - name: Build win-portable
              run: npm run-script win

            - name: Upload artifacts
              uses: actions/upload-artifact@v3.1.0
              with:
                name: windows-artifacts
                path: |
                  dist/*/resources/app.asar
                  dist/pokeclicker-desktop-*.exe

    linux-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "18.x"

            - name: Install Node.js dependencies
              run: npm ci

            - name: Build linux-arm64
              run: npm run-script linux:arm64

            - name: Build linux-x64
              run: npm run-script linux:x64

            - name: Upload artifacts
              uses: actions/upload-artifact@v3.1.0
              with:
                name: linux-artifacts
                path: |
                  dist/pokeclicker-desktop*.deb
                  dist/pokeclicker-desktop*.rpm
